UX-93 Storybook welcome page
marklogic/design-system pull request #48
Opened 2020-05-10 01:30 UTC by phoenixeliot

Initial draft, needs to be hooked in to actually display as the welcome page (probably as an MDX story?)

2020-05-14 05:14 UTC, DanLipsitt requested changes

2020-05-14 05:14 UTC, DanLipsitt commented on stories/Welcome-draft.md
> +- When showing you the source code for a story, StoryBook displays function props as `noRefCheck`, rather than showing the function contents. When copying from these stories, you will have to provide
This is fixed in the new DocsPage Storybook addon.

2020-05-14 05:14 UTC, DanLipsitt commented on stories/Welcome-draft.md
> +A few components must be imported directly from their path, or should be if you want tree-shaking (like with {linkTo('MLIcon')}):
How do we tell which components we need to do this with?

2020-05-14 05:14 UTC, DanLipsitt commented on stories/Welcome-draft.md
> +## How to use these components
I assume we don't need install info if people are getting the library from npm?

2020-05-14 05:14 UTC, DanLipsitt commented on stories/Welcome-draft.md
> +# Welcome to the MarkLogic Design System Storybook
It might make sense to have a brief overview of what this storybook contains and what it is for.

2020-05-14 05:29 UTC, phoenixeliot commented on stories/Welcome-draft.md
> +- When showing you the source code for a story, StoryBook displays function props as `noRefCheck`, rather than showing the function contents. When copying from these stories, you will have to provide
I'll update this text when that gets merged, then

2020-05-14 05:30 UTC, phoenixeliot commented on stories/Welcome-draft.md
> +## How to use these components
I'm confused what you mean here, and which part of the code above you're referring to

2020-05-14 21:32 UTC, phoenixeliot commented on stories/Welcome-draft.md
> +A few components must be imported directly from their path, or should be if you want tree-shaking (like with {linkTo('MLIcon')}):
I've updated it to just be about icons; the others are ones you don't need to be using directly anyway.

2020-05-14 21:38 UTC, DanLipsitt commented on stories/Welcome-draft.md
> +## How to use these components
I thought I deleted this comment. Nothing to see here... 😊

2020-05-14 21:39 UTC, DanLipsitt commented on stories/Welcome-draft.md
> +## How to use these components
(ML said in our last call that we can assume that library install is documented elsewhere.)

2020-05-14 21:41 UTC, DanLipsitt submitted a review, later dismissed
All good now. (Pending integration to display properly in the storybook.)

2020-05-14 21:56 UTC, DanLipsitt commented
@phoenixeliot Possibly another quirk for the gotchas list: icons will look different in the storybook code view depending on which icon set they’re from (I think?). For example, `<MLIcon.Route />` gets rendered as `<route />` and <MLIcon.SearchOutlined /> gets rendered as `<SearchOutlined />` . Things will work fine if they follow your instructions, but I’m not sure what will happen if they try to paste `<route />` , so you may want a specific warning about that. It might also be worth noting that following the Ant Icon docs may not work.

2020-05-26 04:41 UTC, brucean52 submitted a review, later dismissed

2020-05-26 15:43 UTC, phoenixeliot commented
I updated the text to reflect how FontAwesome icons should be accessed. I fixed the icon displayName capitalization in another branch (26_result), so I've moved that small fix here so the documentation is at least accompanied by the thing that makes it correct.

2020-05-26 23:12 UTC, brucean52 approved these changes

2020-05-26 23:12 UTC, merged